# Generated by Django 2.1.2 on 2019-01-21 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('23d71977-07bd-4c18-9bad-ba38be526af2'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('ai_config', models.CharField(max_length=16, null=True)),
                ('status', models.CharField(max_length=16)),
                ('board_string', models.CharField(default=None, max_length=2048)),
                ('current_turn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameStateHash',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('07606650-21fc-4b66-8252-845ebb52fa15'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('game_type', models.CharField(editable=False, max_length=8)),
                ('game_state_hash', models.TextField(editable=False)),
                ('board_metrics', models.TextField(editable=False)),
                ('white_queen_neighbours', models.TextField(editable=False)),
                ('black_queen_neighbours', models.TextField(editable=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gamestatehash',
            unique_together={('game_state_hash', 'board_metrics', 'white_queen_neighbours', 'black_queen_neighbours')},
        ),
    ]
