# Generated by Django 2.1.2 on 2018-12-03 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzinga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_string',
            field=models.CharField(default=None, max_length=2048),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e753289a-d9f5-4edc-b126-03eb2bfe1eb0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
