# Generated by Django 2.1.2 on 2018-12-04 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzinga', '0002_auto_20181204_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_config',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7de27d1a-b037-429a-b2ba-03b349ee8134'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
