# Generated by Django 2.1.2 on 2018-12-04 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzinga', '0003_auto_20181204_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dbfc0756-d482-441a-9329-2b96f549dba1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
