# Generated by Django 2.1.2 on 2018-12-04 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzinga', '0005_auto_20181204_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ac3bf6f-ff82-4f00-9284-3b626610ce4a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
