# Generated by Django 2.1.2 on 2018-12-04 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzinga', '0006_auto_20181204_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b28600d-5514-448c-858e-7cb4f0a68008'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
