# Generated by Django 2.1.2 on 2018-12-04 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzinga', '0007_auto_20181204_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2f4af03-5c79-4d90-971f-7372dc22640b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
