# Generated by Django 2.1.2 on 2018-12-04 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzinga', '0009_auto_20181204_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b352e993-45df-4347-8a99-b20be9505c6a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
